plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
author: Oscar Olivetti
description: Sitio web personal
lang: en
locale: en_GB
url: "https://oiuhukt.github.io/failosophy"
baseurl: ""

# RSS feeds
feed:
  posts_limit: 20
