baseurl: /failosophy
sass:
  sass_dir: _sass
  style: compressed
title: failosophy
subtitle: The blog about nothing
author: Abraham Olivetti
simple_search: https://duckduckgo.com/
description: A blog about nothing
name: tufte
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: America/Mexico_City
excerpt_separator: <!--more--> # you can specify your own separator, of course.
exclude:
  ["Gemfile", "Gemfile.lock", "Rakefile", "UploadToGithub.Rakefile", "README.md"]
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
